timeout: 3

/bentobox
    protocol: limine
    path: boot():/boot/kernel
    resolution: 1024x768

/bentobox (nosmp)
    protocol: limine
    path: boot():/boot/kernel
    resolution: 1024x768
    cmdline: nosmp