Section "Extensions"
    Option "MIT-SHM" "Disable"
EndSection

Section "Module"
    Load "shadow"
    Load "fbdevhw"
    Load "fbdev"
EndSection

Section "Device"
    Identifier "Card0"
    Driver "fbdev"
    Option "fbdev" "/dev/fb0"
    Option "ShadowFB" "false"
EndSection