#!/bin/bash
set -e
./ports/xorgproto.sh
./ports/xorg-util-macros.sh
./ports/xtrans.sh
./ports/libXau.sh
./ports/libXdmcp.sh
./ports/libpthread-stubs.sh
./ports/xcb-proto.sh
./ports/libxcb.sh
./ports/libX11.sh
./ports/libXext.sh
./ports/libXfixes.sh
./ports/libXrender.sh
./ports/zlib.sh
./ports/freetype.sh
./ports/font-util.sh
./ports/libfontenc.sh
./ports/libXfont2.sh
./ports/pixman.sh
./ports/libxkbfile.sh
./ports/libxcvt.sh
./ports/nettle.sh
./ports/xkeyboard-config.sh
./ports/libxkbcomp.sh
./ports/xorg-server.sh
./ports/xf86-video-fbdev.sh
./ports/xf86-input-keyboard.sh
./ports/xf86-input-mouse.sh

./ports/libXrandr.sh
./ports/libXi.sh
./ports/libICE.sh
./ports/libSM.sh
./ports/libXt.sh
./ports/libXmu.sh
./ports/libXpm.sh
./ports/libXaw.sh
./ports/expat.sh
./ports/fontconfig.sh
./ports/libXft.sh
./ports/libevent.sh
./ports/libxkbcommon.sh
./ports/libxml2.sh
./ports/libiconv.sh
./ports/libpng.sh