#pragma once

#define PF_UNSPEC	0
#define PF_LOCAL	1
#define PF_UNIX		PF_LOCAL
#define PF_FILE		PF_LOCAL
#define PF_INET		2
#define PF_AX25		3
#define PF_IPX		4
#define PF_APPLETALK	5
#define PF_NETROM	6
#define PF_BRIDGE	7
#define PF_ATMPVC	8
#define PF_X25		9
#define PF_INET6	10
#define PF_ROSE		11
#define PF_DECnet	12
#define PF_NETBEUI	13
#define PF_SECURITY	14
#define PF_KEY		15
#define PF_NETLINK	16
#define PF_ROUTE	PF_NETLINK
#define PF_PACKET	17
#define PF_ASH		18
#define PF_ECONET	19
#define PF_ATMSVC	20
#define PF_RDS		21
#define PF_SNA		22
#define PF_IRDA		23
#define PF_PPPOX	24
#define PF_WANPIPE	25
#define PF_LLC		26
#define PF_IB		27
#define PF_MPLS		28
#define PF_CAN		29
#define PF_TIPC		30
#define PF_BLUETOOTH	31
#define PF_IUCV		32
#define PF_RXRPC	33
#define PF_ISDN		34
#define PF_PHONET	35
#define PF_IEEE802154	36
#define PF_CAIF		37
#define PF_ALG		38
#define PF_NFC		39
#define PF_VSOCK	40
#define PF_KCM		41
#define PF_QIPCRTR	42
#define PF_SMC		43
#define PF_XDP		44
#define PF_MCTP		45

#define SOCK_STREAM     1
#define SOCK_DGRAM      2
#define SOCK_RAW        3
#define SOCK_RDM        4
#define SOCK_SEQPACKET  5
#define SOCK_DCCP       6
#define SOCK_PACKET     10

#define SOCK_CLOEXEC    02000000
#define SOCK_NONBLOCK   00004000

int unixsocket_new(int type);