name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - with:
      submodules: recursive
      fetch-depth: 0

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y build-essential nasm grub-pc-bin xorriso mtools genext2fs curl musl

    - name: Run check
      run: make -j$(nproc)